import type { Locale } from "./quiz-types";
import type { Messages, SeoRouteKey } from "../i18n/catalog";

export const SEO_PROD_ORIGIN = "https://kpopquiz.online";
export const SEO_DEFAULT_PATH = "/pt-br/";

// Open Graph cards: one PNG per indexable route, committed under
// web/public/og/ and regenerated by scripts/generate-og.mjs (ADR 021).
export const SEO_OG_IMAGE_DIR = "/og/";
export const SEO_OG_IMAGE_WIDTH = 1200;
export const SEO_OG_IMAGE_HEIGHT = 630;

export interface SeoRoute {
  key: SeoRouteKey;
  locale: Locale;
  path: string;
  alternatePath: string;
}

function pair(
  key: SeoRouteKey,
  ptPath: string,
  enPath: string,
): [SeoRoute, SeoRoute] {
  return [
    { key, locale: "pt-BR", path: ptPath, alternatePath: enPath },
    { key, locale: "en", path: enPath, alternatePath: ptPath },
  ];
}

// Exactly the 14 indexable content routes. The `/` canonical alias, `/data/*`,
// staging builds and `?mode`/`?theme` variants stay out of the index.
export const SEO_ROUTES: readonly SeoRoute[] = [
  ...pair("quiz", "/pt-br/", "/en/"),
  ...pair("grid", "/pt-br/grid/", "/en/grid/"),
  ...pair("connections", "/pt-br/conexoes/", "/en/connections/"),
  ...pair("nameGuess", "/pt-br/adivinhe/", "/en/guess/"),
  ...pair("wordSearch", "/pt-br/caca-palavras/", "/en/word-search/"),
  ...pair("mapPilot", "/pt-br/mapa/", "/en/map/"),
  ...pair("timeline", "/pt-br/linha-do-tempo/", "/en/timeline/"),
];

export function seoAbsoluteUrl(path: string): string {
  return `${SEO_PROD_ORIGIN}${path}`;
}

export function seoOgLocale(locale: Locale): string {
  return locale === "pt-BR" ? "pt_BR" : "en_US";
}

/** The route of `key` in `locale`. Every key has one route per locale. */
export function seoRoute(key: SeoRouteKey, locale: Locale): SeoRoute {
  const route = SEO_ROUTES.find((r) => r.key === key && r.locale === locale);
  if (!route) throw new Error(`no SEO route for ${key} in ${locale}`);
  return route;
}

/**
 * File-safe name of a route, e.g. `pt-br-conexoes` or `en-quiz`. The same
 * names are used by web/public/llms/*.md.
 */
export function seoRouteSlug(route: SeoRoute): string {
  const segments = route.path.split("/").filter(Boolean);
  return segments.length > 1 ? segments.join("-") : `${segments[0]}-quiz`;
}

/**
 * Site-relative path of the OG image of a route. The quiz route is also the
 * home page, so its image is the generic site card; privacy and 404 reuse it.
 */
export function seoOgImagePath(key: SeoRouteKey, locale: Locale): string {
  return `${SEO_OG_IMAGE_DIR}${seoRouteSlug(seoRoute(key, locale))}.png`;
}

export const SEO_OG_TAGLINE: Record<Locale, string> = {
  "pt-BR": "Jogos diários de K-pop com fontes",
  en: "Daily K-pop games with sources",
};

const GAME_NAME_FIELD = {
  quiz: "gameQuiz",
  grid: "gameGrid",
  connections: "gameConnections",
  nameGuess: "gameNameGuess",
  wordSearch: "gameWordSearch",
  mapPilot: "gameMap",
  timeline: "gameTimeline",
} as const satisfies Record<SeoRouteKey, keyof Messages>;

/** Name of the game as the navigation shows it. */
export function seoGameName(key: SeoRouteKey, messages: Messages): string {
  return messages[GAME_NAME_FIELD[key]];
}

/** Alt text of the OG image, describing what the card shows. */
export function seoOgImageAlt(key: SeoRouteKey, locale: Locale, messages: Messages): string {
  const host = new URL(SEO_PROD_ORIGIN).host;
  if (key === "quiz") return `K-pop Quiz. ${SEO_OG_TAGLINE[locale]}. ${host}`;
  const name = seoGameName(key, messages);
  return locale === "pt-BR"
    ? `${name}, jogo diário do K-pop Quiz em ${host}`
    : `${name}, a daily K-pop Quiz game at ${host}`;
}

/** `utm_campaign` of a game: the last segment of its English path. */
export function seoShareCampaign(key: SeoRouteKey): string {
  const segments = seoRoute(key, "en").path.split("/").filter(Boolean);
  return segments.length > 1 ? segments[segments.length - 1]! : "quiz";
}

/**
 * Production URL of a game in the player's language, tagged so analytics can
 * count visits from shared results. Staging shares the same URL: the link
 * points people at the live game, never at the staging host.
 */
export function seoShareUrl(key: SeoRouteKey, locale: Locale): string {
  const params = new URLSearchParams({
    utm_source: "share",
    utm_medium: "social",
    utm_campaign: seoShareCampaign(key),
  });
  return `${seoAbsoluteUrl(seoRoute(key, locale).path)}?${params}`;
}
